### ISSUE TITLE
Processing comment field with nulls

### ISSUE THREAD

**Issue by bll123** [quodlibet/mutagen#267]
MP3 file with the following comment field (as reported by mutagen-inspect version 1.22 on Linux):

COMM=='\x00\x00\x00'=Track 1

On Windows with version 1.33.1 or version 1.34.1, mutagen-inspect (using python 3.4) fails to process the ID3 tags.
Output is only:
C:\Users\bll\Desktop\BallroomDJ\test.dir>"C:\python34\python.exe" "C:\python34\Scripts\mutagen-inspect" "test-files/movingon.mp3"
-- test-files/movingon.mp3
- MPEG 1 layer 3, 192000 bps (CBR?), 44100 Hz, 2 chn, 150.05 seconds (audio/mp3)

**Comment by lazka** [comment]
Can you provide the file? (reiter.chrstoph@gmail.com)

**Comment by bll123** [comment]
[movingon.zip](https://github.com/quodlibet/mutagen/files/487931/movingon.zip)

**Comment by bll123** [comment]
Yup, upload worked this time.

**Comment by lazka** [comment]
Thanks!

**Comment by lazka** [comment]
bisected to 73f7bb689a747d6c5d0253238b89bb29e9f6ed40

**Comment by lazka** [comment]
The values are missing a BOM. We used to use the python utf-16 decoder which falls back to the system byte order (uhh.. why?) in that case. The bisected commit changed it to use the incremental decode which fails in such a case.

We should fall back to utf-16-le in case the BOM is missing. Because

* there is a separate utf-16-be id3 encoding
* the default encoding for Windows is utf-16-le
* my test suite contains a few files where it's utf-16-le with missing BOM
* the file provided here as well
