### ISSUE TITLE
Tag values contain trailing null (in violaton of specification?) in some instances

### ISSUE THREAD

**Issue by cbj4074** [quodlibet/mutagen#379]
```
$ mid3v2 --version
mid3v2 1.3
Uses Mutagen 1.42.1
```

I'll preface this by saying that I'm not entirely sure that this is a "bug", but rather, it may result from a difference of opinion with regard to how the ID3v2 specification is to be interpreted.

In short, I'm wrestling with the Issue described in https://github.com/JamesHeinrich/getID3/issues/121#issuecomment-322059347 .

The gist of the problem is that when getID3 reads tags that `mid3v2` produces, there is a trailing null, which looks something like this (note the extra character after the period and before the closing double-quote, which while appearing as a space here, is actually a null):

```
  ["comment"]=>
  array(1) {
    [0]=>
    string(21) "All rights reserved. "
  }
```

The getID3 author insists that the comment should not be null-terminated, as doing so is in violation of the specification, as described in http://id3.org/id3v2.3.0#Comments . The following note, in http://id3.org/Compliance%20Issues , seems to apply equally to `mid3v2`:

>Extra nullchar in COMM frame: iTunes adds an extra nullchar to the end of the Comments frame.

Isn't that what `mid3v2` is doing, too? Or am I misunderstanding the nature of the compliance violation?

I'm not sure if it is the same or a related issue, but I've observed the same trailing null with the values in other frames (not only IDv3v2 -> Comments), such as `TIT2`, `TPE1`, etc.

In any case, has this issue been discussed before? If so, I'd appreciate a link to the conversation, as I have come up empty thus far when searching.

Thanks in advance!

**Comment by lazka** [comment]
Hm, there are multiple historical reasons involved I think, not sure if I'm remembering everything correctly:

First there are some spec ambiguities, at least to some extend that if you don't read the whole thing you might make a different implementation:

* The v2.4 spec states that utf-8 strings are null terminated, but then explicitly specifies termination in each frame. iTunes does it everywhere for example.
* Multi value frames are NULL separated, and the spec author later clarified that this means there is only NULL between the values and not after the last one. But since the iTunes adds them everywhere and this would strictly mean an empty second value for each frame, iTunes effectively overruled this.

Then, mutagen specific:

* For historical reasons we treat COMM frames like TXXX frames. I think this is from pre v2.4 times where we extended the v2.3 spec to add multi value support in the frame padding for multiple frame types. The v2.3 spec explicitly states that text frames (TXXX) can have optional termination, so we still do the same for COMM.

Conclusion:

If a parser wants to handle real world id3 tags it needs to handle null termination anyway because of iTunes. Since adding termination doesn't hurt and might even help in case of bad/broken parsers I'd say we should keep it as is.

**Comment by cbj4074** [comment]
@lazka Thank you for the prompt reply and thorough explanation!

Your position sounds entirely reasonable.

The getID3 author has done precisely as you suggest, so I'll go ahead and close the issue.

Thanks again for taking the time to explain the history and rationale; I appreciate it tremendously.

And last, but certainly not least, thanks for your work on this most excellent library!
