### ISSUE TITLE
mp4: mutagen(-inspect) fails with "descriptor parsing read too much data"

### ISSUE THREAD

**Issue by chbrown** [quodlibet/mutagen#444]
I'm having trouble processing certain `m4a`-formatted audiobook files after passing them through `ffmpeg` to split chapters into separate files. Oddly, it works just fine for some books that have gone through that process, so it's not necessarily just `ffmpeg` misbehaving, and neither iTunes nor `exiftool` have any complaints about the files. But trying to open them in Python via `mutagen` or using `mutagen-inspect` at the command line both result in the error:
> descriptor parsing read too much data

which arises from https://github.com/quodlibet/mutagen/blob/release-1.44.0/mutagen/mp4/_as_entry.py#L243

I've been using `mutagen` quite a bit but haven't dug into the source yet. I don't know a whole lot about how metadata is embedded in `mp3` or `m4a` files at the byte-level, i.e., besides the functionality that's exposed by `mutagen`'s API and `exiftool`'s commands. How would I go about debugging the issue and working on a patch?

Sorry I can't share the file here; if I could recreate the issue with some non-copyrighted audio, I'd be happy to, but I don't really know where to start in dissecting the file and detecting where, precisely, the error arises.

I'm using the latest `mutagen` on PyPI (`1.44.0`).

**Comment by lazka** [comment]
I'm afraid you either have to provide a file or try to figure out yourself. The first thing would be to see what `cls` is in that context and what `length`, to see which block is parsed and what's the expected size.

**Comment by chbrown** [comment]
Right, I understand, and I'm trying to figure it out myself; towards that end, perhaps you can point me to the requisite background reading on how these blocks are organized / what `mutagen` assumes in terms of proper structure vs. what the specification mandates? I.e., what specs and resources do you `mutagen` developers refer to when designing and implementing this in the first place? (I'm no stranger to Python or reading specs, but definitely a newbie w.r.t. the nitty gritty of audio file encodings.) Thanks in advance!

FWIW, in my case `mutagen` raises multiple exceptions: most immediately, the `DescriptorError`, which I noted above, during handling of which it raises an `ASEntryError`, and in handling that it raises a `MP4StreamInfoError`.

**Comment by lazka** [comment]
This is all defined in various parts and amendments of the mpeg4 iso spec: https://en.wikipedia.org/wiki/MPEG-4#MPEG-4_Parts which isn't freely available.

**Comment by jmeosbn** [comment]
In case it's any help, this happens when converting some more recent drm'd books from audible that are 128kbps and 44100Hz (file name ending _ep7.aax)

Mutagen can read the metadata from the downloaded drm'd file (aax) but not the file output using ffmpeg to remove the drm (using your own purchase id to decrypt).

One data structure (DecoderSpecificInfo) is failing mutagen's checks despite creating the instance with apparently correct info.

I can confirm the same books, at their earlier bitrate have no issues (that is, ep6: 64 / 22050 and ep7 @ 44100)

I have observed this for a while but only in the past few days have I dug into the code, as I purchased a book that I could not also get as 64kbps.

I've tried lots of things as a workaround to "rewrite" the file, L-SMASH ignored the error and wrote a usable file if I selected something like MP4A or another as the output format. AtomicParsley nope, neither ffmpeg (changing various settings but using audio copy)

So I've disabled that exception and print an error instead for the cases I've consistently observed:

- TAG == 5 and audioObjectType == 2

- channelConfiguration == channels

- samplingFrequency == sample_rate

- sample_rate and channels have actual values

My printed error has always the same values (in brackets) from a seemingly valid instance, and the actual values are as expected.

```
instance: mutagen.mp4._as_entry.DecoderSpecificInfo object at 0xb603c390>

x descriptor parsing read too much data (-02)
x length: 2, tell: 35, pos: 31 == [2, 35, 31]
```

Finally... I can also confirm that a snippet of the file exhibits the problem so can email a sample 2 secs of ep7+9 which is < 150Kb.

Let me know if you want any testing or info. I'm familiar with PRs etc. so with a bit of help I can try some fixes out on about 5 purchases I have available in 128/44100.

**Comment by lazka** [comment]
> Finally... I can also confirm that a snippet of the file exhibits the problem so can email a sample 2 secs of ep7+9 which is < 150Kb.

please -> reiter.christoph@gmail.com

**Comment by lazka** [comment]
Thanks.

I've had a quick look and comparing with the spec, and assuming I didn't miss anything (which might as well be) the file contains invalid lengths for the DecoderSpecificInfo and DecoderConfigDescriptor structs, being smaller than their content.

We could infer the size based on the content in that case, so that might be a workaround. I'll have to think about that.

**Comment by chbrown** [comment]
👍 checked out your branch locally and can confirm that #465 resolves my issue. Thanks! 😄

**Comment by lazka** [comment]
Thanks for testing!
