### ISSUE TITLE
Sometimes mutagen repackages the whole file?

### ISSUE THREAD

**Issue by SharkyRawr** [quodlibet/mutagen#527]
I have this issue where I'm trying to write a video-file tagging utility and it seem's that mutagen is sometimes (not always) reading and rewriting the whole file. I don't know if this is intended or if my mp4 video files are wonky. `video.save()` sometime's takes 5 minutes with large (>5GB) video files which is rather bothersome in an UI.

This is what my code looks like:

```
def update_file(path: str, m: Metadata):
    video = MP4(path)
    video['\xa9nam'] = m.Title
    video["\xa9wrt"] = m.Director
    video['cprt'] = [m.Maker, m.Label]
    video['\xa9day'] = m.ReleaseDate

    video["\xa9ART"] = m.Actors
    video['\xa9gen'] = m.Genres

    video['covr'] = [MP4Cover(m.Image)]

    video.save()
```

**Comment by lazka** [comment]
Maybe related to https://mutagen.readthedocs.io/en/latest/user/padding.html

**Comment by SharkyRawr** [comment]
I played around with it but it seems it still needs to read the whole file and save it back. Hmmmm.

**Comment by phw** [comment]
@SharkyRawr The tags are for most formats located somewhere at the beginning of the file. If you write new tag data that doesn't fit into the available space the entire file needs to be rewritten. There is not really a way around that.

To mitigate the problem most software writing tags leaves some additional free space, the padding. So even if on an update the tag data is a bit larger it still can fit into the reserved space. But if it doesn't fit the file needs to be rewritten again.

That's why you experience the rewriting sometimes, but not always.

**Comment by SharkyRawr** [comment]
Ah I see, dang. Thank you for the clarification! I'm writing a cover picture to the metadata, I guess that puts the padding requirement above what most files already have. Hm I'll have to rethink this. Thanks!

**Comment by phw** [comment]
Yes, indeed. Writing cover art is most often a reason for resizing. Cover art is at least several hundred kilobytes, maybe even several megabytes. Unless one is replacing existing cover art that often requires a larger tag section.

**Comment by SharkyRawr** [comment]
Is there a possibility of having a progress report? Rewriting 6GB mp4 files can sometimes take a long time and it would be nice to know how far along it is.
