### ISSUE TITLE
cannot tag .wav file with mutagen.id3.WAVE

### ISSUE THREAD

**Issue by maphouse** [quodlibet/mutagen#545]
I have a WAV file in which I already added a few dummy tags using foobar2000
Trying to add tags using mutagen now I'm having difficulty

```
>>> wlist = glob('*.wav')
>>> w = wlist[0]
>>> WAVE(w)
{'TIT2': TIT2(encoding=<Encoding.UTF16: 1>, text=['Little By Little (Waste Wisely Edit)']), 'TPE1': TPE1(encoding=<Encoding.UTF16: 1>, text=['The Marias']), 'TXXX:initialkey': TXXX(encoding=<Encoding.UTF16: 1>, desc='initialkey', text=['HI'])}
>>> WAVE(w).tags.add(TKEY(encoding=3, text=['Abm']))
>>> WAVE(w).save()
>>> WAVE(w)
{'TIT2': TIT2(encoding=<Encoding.UTF16: 1>, text=['Little By Little (Waste Wisely Edit)']), 'TPE1': TPE1(encoding=<Encoding.UTF16: 1>, text=['The Marias']), 'TXXX:initialkey': TXXX(encoding=<Encoding.UTF16: 1>, desc='initialkey', text=['HI'])}
```

I tried another technique which seemed to be suggested in https://github.com/quodlibet/mutagen/issues/392 where I deleted all the tags, and then try to add new ones using only mutagen, but I get an error

```
>>> mutagen.wave.delete(w)
>>> WAVE(w)
{}
>>> WAVE(w).add_tags()
>>> WAVE(w).tags.add(TKEY(encoding=3, text=['Abm']))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'add'
```

Any assistance would be much appreciated!

**Comment by phw** [comment]
The issue here was that there was always a new `WAVE` object created in the code. So there is a call to `WAVE(w).add_tags()`, that creates a `WAVE` object and adds tags to it. But as the object is not assigned it gets discarded again. Then the next call `WAVE(w).tags.add(...)` creates a new object and tries to access it `tags`, but if the loaded file does not have tags this of course fails again.

Something like this would work:

```python
wave = WAVE(w)
if not wave.tags:
    wave.add_tags()
wave.tags.add(TKEY(encoding=3, text=['Abm']))
wave.save(w)
```
