### ISSUE TITLE
How to add multiple tags for mp4 file

### ISSUE THREAD

**Issue by rickyrorton** [quodlibet/mutagen#548]
Like #310 i would like to add multiple artists but for a mp4 file how can i do this?

**Comment by gotcha9999** [comment]
audio["©ART"] = ["Artist1", "Artist2"]

**Comment by rickyrorton** [comment]
i did that but in windows explorer and groove music player its only showing one of the artists

**Comment by phw** [comment]
I don't think those players do support multiple values for artist tags, even for other formats. Also there is a controversy how multiple values in MP4 files actually are supposed to work, because this is not really specified and different tools went different ways of handling it.

See also the discussion at https://tickets.metabrainz.org/browse/PICARD-376?focusedCommentId=35598&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-35598

**Comment by rickyrorton** [comment]
Code:
![image](https://user-images.githubusercontent.com/74890659/149501739-e5323c30-79fe-4a61-8115-ae18663a4b7a.png)
Output:
![image](https://user-images.githubusercontent.com/74890659/149502064-3ec80054-0a04-43f9-85ba-53548fa7a695.png)

**Comment by phw** [comment]
If your goal is to have this displayed in Microsoft tools than you will need to combine the artist names into a single value.

**Comment by rickyrorton** [comment]
Yeah I think adding all as a single string is better 

Thanks for your help and also your contirbution to the source code
