### ISSUE TITLE
Write into FLAC files via cli

### ISSUE THREAD

**Issue by foremtehan** [quodlibet/mutagen#576]
I use mid3v2 cli to write tags, But looks like it only working for mp3 files

`mid3v2 --artist "Fly Away" "01 A Million Miles Away.flac"`

I won't get any error but tags never written. same for m4a files.

**Comment by lazka** [comment]
mid3v2 was mainly created to provide modern/less buggy version of id3v2. id3 tags can be added to any file type since they are just prefixed, but ideally you would only use them on file types where this is also expected and supported by other software.

For flac I'd use metaflac: https://xiph.org/flac/documentation_tools_metaflac.html
