### ISSUE TITLE
mid3v2 produces file that mutagen can't read again

### ISSUE THREAD

**Issue by xeals** [quodlibet/mutagen#634]
Encountered with at least `opus` and `aac` (`m4a` container) audio. Reproducible with:

```sh
$ yt-dlp --extract-audio --audio-format opus --output file.opus <any YouTube URL>
$ mid3v2 -a art -A alb -T 1 file.opus
$ mutagen-inspect file.opus
-- file.opus
can't sync to MPEG frame
$ mid3v2 -l file.opus
IDv2 tag into for file.opus
TALB=alb
TPE1=art
TRCK=1
```

`mutagen-inspect` is used as an example of other programs that use Mutagen as a library, which this also affects.

**Comment by phw** [comment]
Please see https://github.com/quodlibet/mutagen/issues/604

That's because m*id3*v2 is a utility to work with ID3 tags and is adding ID3 tags to the files. It should not be used on non-ID3 formats like opus.

Ideally the command should refuse to modify the Opus file, but currently it just adds the tags.
